
model_file: src/models/lightgbm.py

model_class:
  _target_: models.lightgbm.LightGBM


train:
  boosting_type: gbdt
  objective: regression
  metric: "{l2, l1}"
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  verbose: 0
