exclude: ".torrent$"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
  - id: debug-statements
    language_version: python3
- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
  - id: black
    language_version: python3.12
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: isort (python)
    args: ["--profile", "black"]
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
- repo: https://github.com/iterative/dvc
  rev: 3.48.1
  hooks:
  - id: dvc-pre-push
    additional_dependencies: ['.[s3]']
    language_version: python3.12
    stages:
    - push
  - id: dvc-post-checkout
    additional_dependencies: ['.[s3]']
    language_version: python3.12
    stages:
    - post-checkout
    always_run: true
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
    - id: mypy
      additional_dependencies: [types-PyYAML]
- repo: local
  hooks:
  - id: check-aim-db
    name: check-aim-db
    entry: check_aim_update.sh
    language: script
