vars:
  - ../config/config.yaml
  - model_config: config/model/xgboost.yaml
  - preprocess_config: config/preprocessing/iris.yaml

artifacts:
  iris_model:
    type: model
    path: ${model_path}

stages:

  import_data:
    wdir: ".."
    cmd: python3 src/import_data.py
    deps:
      - src/import_data.py
      - config/config.yaml
    outs:
      - ${dataset}

  prepare_training_data:
    wdir: ".."
    cmd: python3 src/prepare_training_data.py
    deps:
      - src/prepare_training_data.py
      - ${preprocess_config}
      - config/config.yaml
      - ${dataset}
    params:
      - ${preprocess_config}:
        - train_fraction
    outs:
      - ${training_dataset}

  hyperparameter_tuning:
    frozen: True
    wdir: ".."
    cmd: "python3 src/train.py -m $(yq '.trials' config/model/xgboost.yaml | sed 's/^/model.train./' | sed 's/: /=/g' | tr '\\n' ' ')"
    deps:
      - src/train.py
      - ${training_dataset}
      - config/config.yaml
      - ${model_config}
      - ${preprocess_config}
    outs:
      - multirun/optimization_results.yaml

  train:
    wdir: ".."
    cmd: "python3 src/train.py $(yq '.best_params' multirun/optimization_results.yaml | sed 's/: /=/' | tr '\\n' ' ')"
    params:
      - ${model_config}:
        - train
    deps:
      - multirun/optimization_results.yaml
      - src/train.py
      - ${model_file}
      - ${training_dataset}
      - config/config.yaml
      - ${model_config}
      - ${preprocess_config}
    outs:
      - ${model_path}
    metrics:
      - ${metrics_file}
