vars:
  - ../params.yaml
artifacts:
  iris_model:
    type: model
    path: ${model_path}
stages:
  import_data:
    wdir: ".."
    cmd: python3 src/import_data.py
    deps:
      - src/import_data.py
      - config/config.yaml
    outs:
      - ${dataset}
  prepare_training_data:
    wdir: ".."
    cmd: python3 src/prepare_training_data.py
    deps:
      - src/prepare_training_data.py
      - config/preprocessing/${hydra.runtime.choices.preprocessing}.yaml
      - config/config.yaml
      - ${dataset}
    params:
      - preprocessing.train_fraction
    outs:
      - ${training_dataset}
  hyperparameter_tuning:
    frozen: True
    wdir: ".."
    cmd: "python3 src/train.py -m $(yq '.trials' config/model/${hydra.runtime.choices.model}.yaml | sed 's/^/model.train./' | sed 's/: /=/g' | tr '\\n' ' ')"
    deps:
      - src/train.py
      - ${training_dataset}
      - config/config.yaml
      - config/model/${hydra.runtime.choices.model}.yaml
      - config/preprocessing/${hydra.runtime.choices.preprocessing}.yaml
    outs:
      - multirun/optimization_results.yaml
  train:
    wdir: ".."
    cmd: "python3 src/train.py $(yq '.best_params' multirun/optimization_results.yaml | sed 's/: /=/' | tr '\\n' ' ')"
    params:
      - model.train
    deps:
      - multirun/optimization_results.yaml
      - src/train.py
      - config/config.yaml
      - ${model.model_file}
      - ${training_dataset}
      - config/model/${hydra.runtime.choices.model}.yaml
      - config/preprocessing/${hydra.runtime.choices.preprocessing}.yaml
    outs:
      - ${model_path}
    metrics:
      - ${metrics_file}
